spring.application.name=product-api
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost/db_product
spring.datasource.username=postgres
spring.datasource.password=postgres

app.promotion.message=Chirstmas Promotion

#spring.profiles.actives=es

spring.claud.consul.host=localhost
spring.claud.consul.port=8585

spring.config.import=optional:consul:
